import type { Metadata } from "next";
import "./globals.css";
import { Mingzat } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mingzat = Mingzat({
  subsets: ['latin'],
  weight: "400"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mingzat.className} bg-black text-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
